- name: Commit and push changes
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add sub_auto.txt
          git pull --rebase origin main
          git commit -m "Auto-update configs" || exit 0
          git push
